# config

# interval in mins
interval: 30

bbdc:
  username:
    # "1234567890"
  password:
    # '123456'

telegram:
  token: "5594242872:AAFEEfjCh5-crMAQdIQrASYBPfyumPBdyw4"
  chat_id: "-793162416"

month_list: ["Jan'23", "Feb'23", "Mar'23", "Apr'23", "May'23"]
